---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/commit-id: 1f8daf0543d15799ec6ff46bf5156ef2ad03345e
    app.quarkus.io/build-timestamp: 2023-04-13 - 21:43:34 +0000
  labels:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: quarkus-demo
      app.kubernetes.io/version: 1.0.0-SNAPSHOT
  template:
    metadata:
      annotations:
        app.quarkus.io/commit-id: 1f8daf0543d15799ec6ff46bf5156ef2ad03345e
        app.quarkus.io/build-timestamp: 2023-04-13 - 21:43:34 +0000
      labels:
        app.kubernetes.io/name: quarkus-demo
        app.kubernetes.io/version: 1.0.0-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: janis/quarkus-demo:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          name: quarkus-demo
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    app.quarkus.io/commit-id: 1f8daf0543d15799ec6ff46bf5156ef2ad03345e
    app.quarkus.io/build-timestamp: 2023-04-13 - 21:43:34 +0000
  labels:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  name: quarkus-demo
spec:
  ports:
    - name: http
      nodePort: 31974
      port: 80
      protocol: TCP
      targetPort: 8081
  selector:
    app.kubernetes.io/name: quarkus-demo
    app.kubernetes.io/version: 1.0.0-SNAPSHOT
  type: NodePort
